version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
        RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
    - 'rabbitmq_data:/data'

volumes:
  rabbitmq_data:
